config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :show, :edit, :create, :new, :update, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  root to: 'homes#top'
  get 'home/about'=>'homes#about'
  #get 'users/new'=>'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_one_attached :profile_image
  
  validates :title, presence: true
  validates :body, presence: true 
  
  validates :body,length: { maximum: 200 }
  
   def get_profile_image(width,height)
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     profile_image.variant(resize_to_limit: [width,height]).processed
   end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
  
    validates :name, presence: true
    validates :name,length: { minimum: 2 }  
    validates :name,length: { maximum: 20 }
    validates :name, uniqueness: true
    validates :introduction, length: { maximum: 50 }
      
    
   
   def get_profile_image(width,height)
    unless profile_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     profile_image.variant(resize_to_limit: [width,height]).processed
   end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top,:about]
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end 
  
  def after_sign_out_path_for(resource)
     root_path
  end
  
  def after_log_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
 def new
  @book=Book.new
  if @book.user!=current_user
   redirect_to books_path
  end 
 end 
 
 def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
    flash[:notice] = 'You have created book successfully.'
    redirect_to book_path(@book.id)
    else
     @books=Book.all
     @user=current_user
     render :index
    end 
 end
 
 def index
  @books=Book.all
  @book=Book.new
  @user=current_user
 end 
 
 
 def edit
  @book=Book.find(params[:id])
  if @book.user!=current_user
   redirect_to books_path
  end  
 end  
 
 def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = 'Book was successfully updated.'
    redirect_to book_path(@book.id)
    else
    @user=current_user
    render :edit
    end 
 end  
 
 def show
  @book=Book.find(params[:id])
  @user=@book.user
  @book_new=Book.new
 end 
 
 def destroy
  book=Book.find(params[:id])
  book.destroy
  redirect_to '/books'
 end  
 
 private

 def book_params
  params.require(:book).permit(:title, :body)
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

 def top
 end   

 def about
 end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def show
  @book=Book.new
  @user=User.find(params[:id])
  @books=@user.books
 end
 
 
 def edit
  @user=User.find(params[:id])
  if @user!=current_user
  redirect_to user_path(current_user)
  end 
 end
 
 
 def update
  @user=User.find(params[:id])
  if@user.update(user_params)
  flash[:notice] = 'You have updated user successfully.'
  redirect_to user_path(current_user.id)
  else
  render :edit
  end
 end  

def index
 @users=User.all
 @user=current_user
 @book=Book.new
end 
 
 
 private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<h2>User info</h2>
 <%= image_tag user.get_profile_image(100,100) %> 
 
 

 <table class="table">
  <tbody>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</tbody>
</table>

<%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
 <i class="fas fa-user-cog"></i>
 <% end %>
 
 
 <h2 class="mt-3">New book</h2>
 <%= form_with model: book, local: true do |f| %>
 
 
 <label for="book_title">Title</label>

 
   <div class="input">
    <%= f.text_field :title %>
   </div>
 
 
<div class="form-group">
 <label for="book_opinion">Opinion</label> 
  <div class="input">
  <%=f.text_area :body %>
  </div>
  </div>
  
  <%=f.submit'Create Book',class:"btn btn-success"%>
<% end %>

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<% if @book.errors.any? %>
 <h2><%=@book.errors.count %>errors prohibited this obj from being saved:</h2>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
   </ul>
<% end %>   

<h1>Editing Book</h1>

<%=form_with model: @book, url: book_path(@book.id),method: :patch do |f| %>

<div class="form-group">
<label for="book_title">title</label>
<div class="input">
<%= f.text_field :title %>
</div>
</div>

<div class="form-group">
<label for="book_opinion">opinion</label>
<div class="input">
<%= f.text_area :body %>
</div>
</div>

<div class="form-group">
<%= f.submit'Update Book',class:"btn btn-success" %>
</div>

<% end %>

<%=link_to "Show", book_path(@book.id) %>

<%=link_to "Back", books_path %>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
 <div id="error_explanation">
 <% if @book.errors.any? %>
 <h2><%=@book.errors.count %>errors prohibited this obj from being saved:</h2>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
   </ul>
<% end %>   
</div>

<div class="row">
<div class="col-md-3">

<%=render'books',book: @book, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse"> 
 <thead>
  <th></th>
 <th>Title</th>
 <th>Opinion</th>
 <% @books.each do |book| %>
 <tr>
 <td>
  <%= link_to user_path(book.user.id) do %>
  <%=image_tag book.user.get_profile_image(100,100) %>
  <% end %>
  </td> 
 <td><%=link_to book.title ,book_path(book.id) %></td>
 <td><%=book.body %></td>
 <% end %>
 </tr>
 </thead>
</table>

</div>
</div>

app/views/books/new.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<h2>User info</h2>
<div>
 <%=image_tag 'no_image.jpg' %>
 <%= link_to edit_user_path(current_user.id), class:"btn btn-outline-secondary btn-block" do %>
 <i class="fa fa-users-cog"></i>
 <% end %>
 
</div>
<table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th></th>
  </tr>
</tbody></table>





<h2 class="mt-3">New Book</h2>
<%= form_with model: @book do |f| %>
 <h4>Title</h4>
  <%=f.text_field:title %>
 <h4>Opinion</h4> 
  <%=f.text_area :body %>
  <%=f.submit'Create Book'%>
<% end %>
</div>


<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table> 
 <thead>
 <th>Title</th>
 <th>Opinion</th>
 

 </thead>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">


<%=render'books',book: @book_new, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table">
  <tr>
<td><%= image_tag @book.user.get_profile_image(100,100) %>
<br><%= link_to @user.name ,user_path(@user.id)%>
</td>    
<td><%=link_to @book.title  %></td>
<td><%=@book.body %></td>


<% if @user==current_user %>
<td><%=link_to"Edit" , edit_book_path(@book.id) ,class:"btn btn-success"%></td>
<td><%=link_to"Destroy" ,book_path(@book.id),method: :delete ,class:"btn btn-sm btn-danger"%></td>
<% else %>
 <td></td>
 <td></td>
<% end %> 
  </tr>
</table>
</div>
</div>

app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i> <strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

app/views/homes/top.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to "<i class="fas fa-book"></i> <strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i> <strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <!--<script src="https://kit.fontawesome.com/a6eebf4e30.js" crossorigin="anonymous"></script>-->

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     
       
       <header>
         
         
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          
          
          <% if user_signed_in? %>
           <li>
           <%= link_to  user_path(current_user), class: "nav-link text-light " do %>
           <i class="fas fa-home"></i>Home
           <% end %>
            </li>
           
           <li>
           <%= link_to  users_path, class: "nav-link text-light" do %>
           <i class="fas fa-users"></i>Users
           <% end %>
            </li>
           
           
           <li>
           <%= link_to  books_path, class: "nav-link text-light" do %>
           <i class="fas fa-book-open"></i>Books
           <% end %>
            </li>
            
            <li>
            <%= link_to  destroy_user_session_path, method: :delete,class: "nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
            </li>
           
           <% else %>
            
             <li>
            <%= link_to  root_path,class: "nav-link text-light" do %>
            <i class="fas fa-home" ></i>Home
            <% end %>
            </li>
            
             <li>
            <%= link_to  home_about_path, class: "nav-link text-light" do %>
            <i class="fas fa-link"></i>About
            <% end %>
            </li>
            
            <li>
            <%= link_to  new_user_registration_path, class: "nav-link text-light" do %>
            <i class="fas fa-user-plus "></i>Sign up
            <% end %>
            </li>
          
          <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i>Log in
                  <% end %>
                </li>

          
            
  
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

       
   
  </header>
    <main>
    <p><%= notice %></p>
    <%= yield %>
    </main>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>
  
   <% if @user.errors.any? %>
 <h2><%=@user.errors.count %>errors prohibited this obj from being saved:</h2>
  <ul>
   <% @user.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
   </ul>
<% end %>   
   
 <%=form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <div class="input">
   <%=f.text_field :name ,autofocus: true, id:"inputName", placeholder:"名前"%>
 </div> 
 <h1></h1>
  <label for="inputImage">Image</label>
 <div class="input"> <%=f.file_field :profile_image,accept: "image/*" %>
 </div>
 <h1></h1>
  <label for="inputIntroduction">Introduction</label>
  <div class="image"><%=f.text_area :introduction %>
  </div>
  <%=f.submit"Update User" ,class:"btn btn-secondary"%>
  <% end %>
   </div>
  </div>
 </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
    
<%=render'books/books',book: @book,user: current_user %>
</div>

<div class="col-md-8 offset-md-1">
<h1>Users</h1>
<table class="table">
<thead>
<th>image</th>
<th>name</th>

<% @users.each do |user| %>

<tr>    
<td><%= image_tag user.get_profile_image(100,100) %> </td>
<td> <%= user.name %></td>
<td> <%= link_to "Show" ,user_path(user.id) %> </td>
</tr>
<% end %>
</thead>
</table>
</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">

<%=render'books/books',book: @book, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table table-hover table-inverse"> 
 <thead>
 <th></th> 
 <th>Title</th>
 <th>Opinion</th>
 <% @books.each do |book| %>
 <tr>
 <td>
  <%=link_to user_path(@user.id) do %>
  <%= image_tag book.user.get_profile_image(100,100) %>
  <% end %>
 </td>
 <td><%=link_to book.title ,book_path(book.id) %></td>
 <td><%=book.body %></td>
 <% end %>
 </tr>
 </thead>
</table>

</div>
</div>